name: tests ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: wmoim/dim_eccodes_baseimage:noble_eccodes-2.44
    env:
      BUFR_ORIGINATING_CENTRE: 65535
      BUFR_ORIGINATING_SUBCENTRE: 65535

    steps:
    - uses: actions/checkout@v4
    - name: Install requirements 📦
      run: |
        pip3 install --upgrade pip                
        pip3 install https://github.com/wmo-im/csv2bufr/archive/master.zip
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt   
        pip3 install .
    - name: run tests ⚙️
      run: |
        pytest
    - name: run flake8 ⚙️
      run: |
        flake8
